### ISSUE TITLE
Training own dataset

### ISSUE THREAD

**Issue by JaxSulav** [omarsalinas16/lipnext#2]
great work. This is not particularly an issue. So, if i want to train it with my own training data, how can i generate the align files for each video that i recorded manually? any sort of reply would be helpful. Thanks

**Comment by osalinasv** [comment]
The GRID Corpus which was the dataset I used has the following structure to their alignment files:

```
0 23750 sil
23750 29500 bin
29500 34000 blue
34000 35500 at
35500 41000 f
41000 47250 two
47250 53000 now
53000 74500 sil
```

The first number is the timestamp of the beginning of the word (or silence period, denoted with `sil`) and the second number the timestamp for the end.

You could manually go over your dataset and write the timestamps and transcriptions for each video if it's small enough. Or you could use any of the available audio speech recognition libraries. You can try with [pocketsphinx](https://github.com/cmusphinx/pocketsphinx).

My particular implementation of lipnet does not use the timestamps, just the text. But you might want to experiment with the times too.

Hope this helped a bit!

**Comment by JaxSulav** [comment]
Thanks for the suggestion. What do you mean by just the text, is your align files different from GRID corpus align files?

**Comment by osalinasv** [comment]
No, they are the same aligns as in the GRID Corpus but I just extract the words and ignore the numbers before handing that data to the model.

**Comment by JaxSulav** [comment]
OK thanks for the help. :)

**Comment by JaxSulav** [comment]
Hello, so your align file is like this:


bin
blue
at
f
two
now

?? . does this work??

**Comment by JaxSulav** [comment]
if not how did you passed only the text. i m bit confused now hehe

**Comment by JaxSulav** [comment]
Hey,

I just signed the petition "HBO: Remake Game of Thrones Season 8 with
competent writers." and wanted to see if you could help by adding your name.

Our goal is to reach 1,000,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/2tfyXC52c5

Thanks!
Sulav
